stages:
  get_data:
    cmd: python src/stage_01_load_save_data.py --config=config/config.yaml
    deps:
      - src/stage_01_load_save_data.py
      - src/utils/all_utils.py
      - config/config.yaml
    outs:
      - data/cat
      - data/dog
  prepare_base_model:
    cmd: python src/Stage_02_prepare_base_model.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/Stage_02_prepare_base_model.py
      - data
      - src/utils/models.py
      - params.yaml
      - src/utils/all_utils.py
      - config/config.yaml
    outs:
      - artifacts/base_model/VGG16_base_model.h5
      - artifacts/base_model/Updated_VGG16_base_model.h5

  prepare_callback:
    cmd: python src/Stage_03_prepare_callbacks.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/Stage_03_prepare_callbacks.py
      - src/utils/models.py
      - src/utils/callbacks.py
      - config/config.yaml
      - src/utils/all_utils.py
      - artifacts/base_model/Updated_VGG16_base_model.h5
    outs:
      - artifacts/callbacks/checkpoint_cb.cb
      - artifacts/callbacks/tensorboard_cb.cb

  train:
    cmd: python src/stage_04_train_data.py --config=config/config.yaml --params=params.yaml
    deps: 
      - src/stage_04_train_data.py
      - src/utils/all_utils.py
      - src/utils/models.py
      - src/utils/callbacks.py
      - src/utils/data_management.py
      - config/config.yaml
      - data
      - artifacts/base_model/updated_VGG16_base_model.h5
      - artifacts/callbacks/checkpoint_cb.cb
      - artifacts/callbacks/tensorboard_cb.cb
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
      - EPOCHS
      - AUGMENTATION
    outs:
      - artifacts/model

  